PS1='\[\e[0;1;38;5;76m\]\u \[\e[0;1;38;5;26m\]\w \[\e[0m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2) \[\e[0;38;5;22m\]\$ \[\e[0m\]'
eval "$(starship init bash)"

HISTCONTROL=ignoredups:erasedups
HISTFILE=~/.cache/bash/history

PATH=$PATH:$HOME/go/bin
