#bindkey -e # enables emacs keybind
# Automatically added to zsh.initExtra by starship
#eval "$(starship init zsh)"

# highlight selection when cycling with Tab
zstyle ':completion:*' menu select
# use the vi navigation keys in menu completion
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Shift+Tab for accept the autosuggest cycle tru the entire sugestion not the local
# by defualt you can you the forward key(C-f(emacs) or right arrow key)
# bindkey '^[[Z' autosuggest-accept

# # Unbind Ctrl+Shift+p (which switches vim modes)
# bindkey -s '^[[116;6u' ''
# # You can get zsh escape sequences with 'read'

# for auto-notify plugin
export AUTO_NOTIFY_THRESHOLD=5
AUTO_NOTIFY_IGNORE+=("git diff" "lf" "yazi")

PATH=$PATH:$HOME/go/bin

# Automatically added to zsh.initExtra by atuin
#eval "$(atuin init zsh)"
